[phases.setup]
nixPkgs = ["dotnet-sdk_7"]

[phases.install]
cmds = [
  "dotnet restore Backend/PortfolioBackend.csproj"
]

[phases.build]
cmds = [
  "dotnet publish Backend/PortfolioBackend.csproj -c Release -o out",
  "mkdir -p out/wwwroot",
  "cp -r Frontend/. out/wwwroot/"
]

[start]
cmd = "cd out && dotnet PortfolioBackend.dll"
