[phases.setup]
nixPkgs = ["dotnet-sdk_7"]

[phases.install]
cmds = [
  "dotnet restore Backend/PortfolioBackend.csproj"
]

[phases.build]
cmds = [
  "dotnet publish Backend/PortfolioBackend.csproj -c Release -o publish_dir",
  "mkdir -p publish_dir/wwwroot",
  "cp -r Frontend/. publish_dir/wwwroot/"
]

[start]
cmd = "cd publish_dir && ls -la && dotnet PortfolioBackend.dll"
